var uname="Lorule",ytu=null,element=null,x=0,y=0,inst=0;function GET(b,a){var d=new XMLHttpRequest;d.onreadystatechange=function(){4==this.readyState&&200==this.status&&a(this.responseText)};d.open("GET","https://allow-any-origin.appspot.com/"+b,!0);d.send()}
function init(){for(var b=document.querySelectorAll("div.app:not([id='youtube']):not([id='close'])"),a=1;document.querySelectorAll("div.app").length>a;document.querySelectorAll("div.app")[a].style.top=32*a+"px",a++);for(a=0;b.length>a;a++)app.hasOwnProperty(b[a].id)&&(b[a].onclick=function(b,a){x=0>=x?window.innerWidth-425-40:x;for(y=0>=y?0:y;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove();var e=document.createElement("div"),d=document.createElement("div"),
c=document.createElement("embed");d.setAttribute("id","uicloser");d.onclick=function(){for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove()};for(var g=0;Object.keys(app[a]).length>g;c.setAttribute(Object.keys(app[a])[g],app[a][Object.keys(app[a])[g]]),g++);e.setAttribute("name","ui"+a);e.style.transform=e.style.webkitTransform="translate("+(0>=x?window.innerWidth-425-40:x)+"px, "+(0>=y?0:y)+"px)";e.ondblclick=function(){"dragging"==document.querySelector("[name^='ui']").getAttribute("class")?
(document.querySelector("[name^='ui']").setAttribute("class",""),makeUndraggable(document.querySelector("[name^='ui']"))):(document.querySelector("[name^='ui']").setAttribute("class","dragging"),makeDraggable(document.querySelector("[name^='ui']")))};e.appendChild(c);e.appendChild(d);document.body.appendChild(e)}.bind(null,b[a],b[a].id));document.querySelector("div#youtube").onclick=function(a,b,e){ytu=ytu?ytu.match(/^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?\/\&]*).*/).pop():
null;if((""==ytu||null==ytu)&&!e.isTrusted)return!1;for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove();if(""!=ytu&&null!=ytu||!e.isTrusted){x=0>=x?window.innerWidth-600-40:x;y=0>=y?0:y;var c=ytu;ytu=null;e=document.createElement("div");a=document.createElement("div");a.setAttribute("id","uicloser");a.onclick=function(){for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove()};e.ondblclick=function(){"dragging"==document.querySelector("[name^='ui']").getAttribute("class")?
(document.querySelector("[name^='ui']").setAttribute("class",""),makeUndraggable(document.querySelector("[name^='ui']"))):(document.querySelector("[name^='ui']").setAttribute("class","dragging"),makeDraggable(document.querySelector("[name^='ui']")))};e.setAttribute("name","ui"+b);e.style.transform=e.style.webkitTransform="translate("+(0>=x?window.innerWidth-600-40:x)+"px, "+(0>=y?0:y)+"px)";e.innerHTML=GetEmbed(c)}else{x=0>=x?window.innerWidth-600-40:x;y=0>=y?0:y;e=document.createElement("div");a=
document.createElement("div");var c=document.createElement("input"),d=document.createElement("div");a.setAttribute("id","uicloser");a.onclick=function(){for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove()};e.ondblclick=function(){"dragging"==document.querySelector("[name^='ui']").getAttribute("class")?(document.querySelector("[name^='ui']").setAttribute("class",""),makeUndraggable(document.querySelector("[name^='ui']"))):(document.querySelector("[name^='ui']").setAttribute("class",
"dragging"),makeDraggable(document.querySelector("[name^='ui']")))};e.setAttribute("name","ui"+b);e.style.width="600px";e.style.maxHeight="446px";e.style.transform=e.style.webkitTransform="translate("+(0>=x?window.innerWidth-600-40:x)+"px, "+(0>=y?0:y)+"px)";c.setAttribute("type","value");c.setAttribute("placeholder","Enter a YouTube search query/video link");c.setAttribute("id","ytinput");c.style.width="100%";c.style.height="24px";c.style.outline=c.style.border="none";c.onkeydown=function(a,b){if(13==
b.which||13==b.keyCode){b.preventDefault();var c=a.value;if(-1!=a.value.indexOf("youtube.com")||-1!=a.value.indexOf("youtu.be"))return ytu=a.value,document.querySelector("div#youtube").click();a.value="";GET("https://www.youtube.com/results?q="+c.replace(/(\s+|\s)/g,"+").replace(/[\W\+]/g,"")+"&sp=EgIQAQ%3D%3D",function(a){document.querySelector("div#uitc").innerHTML="";a=a.match(/a href="\/watch\?v=(.*?)"/gi);if(!a||""==a)return!1;for(var b=0;a.length-1;b++){if(!a[b])return!1;var c=document.createElement("img"),
e=a[b].substring(17,a[b].length-1);c.src="//img.youtube.com/vi/"+e+"/hqdefault.jpg";c.style.width="33.3%";c.setAttribute("id","youtube"+e);c.onclick=function(a){document.querySelector("input#ytinput").value="Copied youtube.com/v/"+a+" to clipboard!";document.querySelector("input#ytinput").style.color="#777";document.querySelector("input#ytinput").style.fontStyle="italic";new Clipboard("img#youtube"+a,{text:function(a){return"youtube.com/v/"+a}.bind(null,a)});setTimeout(function(a){document.querySelector("input#ytinput").style.fontStyle=
document.querySelector("input#ytinput").style.color=document.querySelector("input#ytinput").value="";ytu="youtube.com/v/"+a;return document.querySelector("div#youtube").click()}.bind(null,a),1500)}.bind(null,e);document.querySelector("div#uitc").appendChild(c)}})}}.bind(null,c);d.style.width="100%";d.style.maxHeight="422px";d.style.overflowX="hidden";d.style.overflowY="auto";d.setAttribute("id","uitc");e.appendChild(c);e.appendChild(d)}e.appendChild(a);document.body.appendChild(e)}.bind(null,document.querySelector("div#youtube"),
"youtube");document.querySelector("div#chat").onmouseover=function(){if(!document.querySelector("[name^='ui']"))return!1;document.querySelector("[name^='ui']").style.pointerEvents="none";document.querySelector("[name^='ui']").style.zIndex="-1"};document.querySelector("div#chat").onmouseout=function(){if(!document.querySelector("[name^='ui']"))return!1;document.querySelector("[name^='ui']").style.zIndex=document.querySelector("[name^='ui']").style.pointerEvents=""};document.querySelector("div#info").onclick=
function(a,b){for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove();x=0>=x?window.innerWidth-480-40:x;y=0>=y?0:y;var c=document.createElement("div"),d=document.createElement("div");d.setAttribute("id","uicloser");d.onclick=function(){for(;document.querySelector("[name^='ui']");)document.querySelector("[name^='ui']").remove()};c.ondblclick=function(){"dragging"==document.querySelector("[name^='ui']").getAttribute("class")?(document.querySelector("[name^='ui']").setAttribute("class",
""),makeUndraggable(document.querySelector("[name^='ui']"))):(document.querySelector("[name^='ui']").setAttribute("class","dragging"),makeDraggable(document.querySelector("[name^='ui']")))};c.setAttribute("name","ui"+b);c.style.width=c.style.height="480px";c.style.transform=c.style.webkitTransform="translate("+(0>=x?window.innerWidth-480-40:x)+"px, "+(0>=y?0:y)+"px)";var f=document.createElement("img");f.setAttribute("src","//s20.postimg.org/mwgrnqkn1/info-ui.png");f.style.width=f.style.height="480px";
c.appendChild(f);c.appendChild(d);document.body.appendChild(c)}.bind(null,document.querySelector("div#info"),"info")}
function makeDraggable(b){element=b;interact(element).draggable({snap:{targets:[interact.createSnapGrid({x:4,y:4})],range:Infinity,relativePoints:[{x:0,y:0}]},inertia:{resistance:5,minSpeed:10,endSpeed:10},restrict:{restriction:"parent",elementRect:{top:0,left:0,bottom:1,right:1}}}).on("dragmove",function(a){x+=a.dx;y+=a.dy;document.querySelector("div#chat").style.pointerEvents=document.querySelector("[name^='ui']").style.pointerEvents="none";a.target.style.webkitTransform=a.target.style.transform=
"translate("+x+"px, "+y+"px)"}).on("dragend",function(a){document.querySelector("div#chat").style.pointerEvents=document.querySelector("[name^='ui']").style.pointerEvents=""})}function makeUndraggable(b){interact(b).draggable(!1)._iEvents={}}function OpenDoodle(){return document.querySelector("div#doodle").click()}function OpenSmilies(){return document.querySelector("div#smilies").click()}function OpenGame(b){}function StartMedia(b){alert(1)}
function OpenMedia(b,a){ytu=decodeURIComponent(clean(b).substr(1));document.querySelector("div#youtube").click()}function OpenByN(b){10001==b&&OpenMedia(0);1E4==b&&OpenDoodle();2E4<=b&&OpenGame(b);"{"==b.charAt(0)&&OpenAyah(JSON.parse(b));return 1}
var app={grid:{src:"//www.xatech.com/web_gear/flash/30004.swf?7VcYp2&cn=435272773",wmode:"transparent",width:"425",height:"600",allowscriptaccess:"always"},doodle:{src:"//www.xatech.com/web_gear/flash/doodle.swf?a12&cn=435272773",wmode:"transparent",width:"425",height:"600",allowscriptaccess:"always"},translate:{src:"//www.xatech.com/web_gear/flash/20034.swf?7VcYp2&cn=435272773",wmode:"transparent",width:"425",height:"600",allowscriptaccess:"always"},trade:{src:"//www.xatech.com/web_gear/flash/30008.swf?7VcYp2&cn=435272773",
wmode:"transparent",width:"425",height:"600",allowscriptaccess:"always"},smilies:{src:"//www.xatech.com/web_gear/flash/smilies.swf?b4&cn=435272773",wmode:"transparent",width:"425",height:"600",allowscriptaccess:"always"}};Element.prototype.remove=function(){this.parentElement.removeChild(this)};NodeList.prototype.remove=HTMLCollection.prototype.remove=function(){for(var b=this.length-1;0<=b;b--)this[b]&&this[b].parentElement&&this[b].parentElement.removeChild(this[b])};
function OpenAyah(b){var a=document.createElement("div"),d=document.createElement("button"),c=document.createElement("div");d.innerText="Close Captcha";c.onclick=d.onclick=function(){document.getElementById("captchab").remove();document.getElementById("captchap").remove()};a.id="captchap";c.id="captchab";c.style.position=a.style.position="absolute";c.style.top=c.style.left="0";a.style.top=a.style.left="50%";a.style.transform="translate(-50%, -50%)";c.style.width=c.style.height="100%";c.style.background=
"rgba(0, 0, 0, .8)";c.style.zIndex="2";a.style.zIndex="3";a.style.overflow="hidden";a.style.borderRadius="24px";a.style.height="483px";d.style.width=a.style.width="482px";d.style.height="20px";var e='<iframe type="text/html" frameborder="0" width="482" height="463" src="http://xat.com/web_gear/chat/AreYouaHuman.php?',h={type:"type",s:"s",i:"i",k:"k",t:"t",r:"roomid"},f;for(f in h)e+=f+"="+parseInt(b[h[f]])+"&";a.innerHTML=e+'"></iframe>';a.appendChild(d);document.body.appendChild(a);document.body.appendChild(c)}
function GetEmbed(b){return'<iframe allowFullScreen="true" rel="noreferrer" src="//www.youtube.com/embed/'+b+'?rel=0&iv_load_policy=3&autoplay=1" width="600" height="446" frameborder="0" />'}function clean(b){return b.replace(/[\?\{\}\"<>:]/g,"")}function createCookie(b,a,d){if(d){var c=new Date;c.setTime(c.getTime()+864E5*d);d="; expires="+c.toGMTString()}else d="";document.cookie=b+"="+a+d+"; path=/"}
function readCookie(b){b+="=";for(var a=document.cookie.split(";"),d=0;d<a.length;d++){for(var c=a[d];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(b))return c.substring(b.length,c.length)}return null};
